---
select_hdmi_output:
  description: "Select hdmi output."
  target:
    entity:
      domain: media_player
  fields:
    hdmi_output:
      description: >-
        Select the HDMI output mode.
      example: "no"
      required: true
      selector:
        select:
          options:
            - "no"
            - "analog"
            - "yes"
            - "out"
            - "out-sub"
            - "sub"
            - "hdbaset"
            - "both"
            - "up"
